### ISSUE TITLE
How to setup default values?

### ISSUE THREAD

**Issue by Y2Kot** [zyv/huawei-lpv2#6]
Hello, I'm trying to run your app with my Huawei band 3 pro.

As I understand, I shoud write smthing like this:
`DEVICE_NAME = "HUAWEI Band 3 Pro-B0D"`

But what should be in 
"device_uuid" field?

Also should I download band.ini anywhere?

**Comment by zyv** [comment]
> Hello, I'm trying to run your app with my Huawei band 3 pro.

Sorry, but the code is most likely not going to work with your Band 3 Pro, unless it is running a very old firmware from circa 2019... Unfortunately, I do not have time to reverse the current protocol.

> As I understand, I shoud write smthing like this: `DEVICE_NAME = "HUAWEI Band 3 Pro-B0D"`

Your understanding is not correct - you don't have to change anything - `DEVICE_NAME` is just an identifier of the default section - you only need to change it if you want to work with multiple devices at the same time.

> Also should I download band.ini anywhere?

You don't need to download anything - `band.ini` will be created automatically if it doesn't exist when you run the script for the first time:

https://github.com/zyv/huawei-lpv2/blob/master/band_lpv2.py#L312

> But what should be in "device_uuid" field?

This field is only used on macOS, because the Bluetooth stack does not return MAC addresses for "privacy" reasons. On Windows / Linux the MAC address is used to connect.

**Comment by zyv** [comment]
No feedback -> resolved.
